### PR TITLE
Add potential fix for broken navigation links

### PR DESCRIPTION
**Pull request by jtomeck**
We'll need to potentially put this live to see if it works or not, but thought maybe we could test it out on the circleci artifiact. If not I recommend merging. Do you agree @manthey ?

### CODE REVIEW

**Comment by jtomeck** [comment]
This did not fix it in the artifacts. Taking another look.

**Comment by manthey** [comment]
@jtomeck I pushed a change to match what you've done with the baseurl for deployment to how the baseurl is specified for the artifacts.  Aside from not adding index.html automatically, if the artifacts work, I think the actual deployment will work.

**Comment by jtomeck** [comment]
I think it should work too. There's still something wonky with it adding '//' in a lot of URLs but I think it still works.

**Comment by jtomeck** [comment]
@manthey the last commit you pushed seems to have completely broken the artifacts. Is this something that we still think will work when we deploy it?

**Comment by manthey** [comment]
I now have some confidence this will work.

**Pull request merged**
