### PR TITLE
Fix contact links.

### LINKED ISSUE #99: Contact Us and Send email links are now broken
The links to Contact Us ad Send Email now have the internal baseurl prefixed to them.

### PR DESCRIPTION
**Pull request by manthey**
This also fixes some remaining double slash links and converts some absolute references into relative references.

Resolves #99.

### CODE REVIEW

**Comment by jtomeck** [comment]
@manthey I did not see this PR before I started working on this, so I have another branch that I haven't published yet with another solution. Do you want me to force delete it or would you like to see what I've done and decide which route we want to go? I'm fine either way.

**Comment by manthey** [comment]
Which of our two solutions do you think will cause the least confusion in the future?  If you think your solution will be easier to figure out when we've forgotten why we've done this, then we should use it (and just keep the other changes I've made in this PR).  Otherwise, we can merge this as it stands and delete your branch.

**Comment by jtomeck** [comment]
> Which of our two solutions do you think will cause the least confusion in the future?

I just decided to push my branch. I think it would cause less confusion for us in the long run, but I wanted your opinion on it. We could always add some comments to what you've done to let us know what the code is doing for us. What do you think?

**Comment by manthey** [comment]
Closing in favor of #102.

**Pull request closed without merging**
